### ISSUE TITLE
potential bug: `#highlight()`

### ISSUE THREAD

**Issue by onkoe** [rose-pine/typst#1]
It seems that `#highlight()` is unaffected by the theme. If that's intentional, I'm sorry for the distraction. Otherwise, a fix would be greatly appreciated! 

Thanks for the incredible package, by the way! This project brings a delightful vibe while I'm working on assignments! :)

<img width="1800" alt="image" src="https://github.com/rose-pine/typst/assets/66580279/8431ddbb-c955-430c-854d-298a73c2ffb4">

**Comment by oplik0** [comment]
It's not *technically* a bug - I wanted to start with the basics (which I mentioned in the typst package PR, but I think not in the readme here even :)

But still - I will expand this package a bit. Typst highlighting is done, but before releasing the next version I'm also working on code syntax highlighting.

**Comment by onkoe** [comment]
awesome! thank you!! 🥰
